import { rankAndMergeFoodSearchResults } from "@/lib/calories/food-search-ranking"
import type { FoodSearchItem } from "@/lib/calories/open-food-facts"

function preparedFood(
  id: string,
  name: string,
  brand: string,
  serving: string,
  servingSizeG: number | null,
  calories: number,
  protein: number | null,
  carbs: number | null,
  fat: number | null,
): FoodSearchItem {
  return {
    food_id: `catalog:${id}`,
    food_name: name,
    brand_name: brand,
    food_type: "Prepared food",
    serving_description: serving,
    serving_size_g: servingSizeG,
    calories,
    protein,
    carbs,
    fat,
    image_url: null,
    source: "catalog",
  }
}

/**
 * High-confidence prepared foods that community product databases commonly
 * omit or index poorly because they do not have a retail barcode.
 */
export const PREPARED_FOOD_CATALOG: FoodSearchItem[] = [
  preparedFood(
    "costco-rotisserie-chicken",
    "Rotisserie Chicken",
    "Costco",
    "3 oz (85 g)",
    85,
    140,
    19,
    0,
    7,
  ),
  preparedFood(
    "costco-chicken-bake",
    "Food Court Chicken Bake",
    "Costco",
    "1 chicken bake",
    null,
    770,
    61,
    81,
    25,
  ),
  preparedFood(
    "costco-cheese-pizza",
    "Food Court Cheese Pizza, slice",
    "Costco",
    "1 slice",
    null,
    710,
    36,
    78,
    27,
  ),
  preparedFood(
    "costco-pepperoni-pizza",
    "Food Court Pepperoni Pizza, slice",
    "Costco",
    "1 slice",
    null,
    650,
    34,
    75,
    24,
  ),
  preparedFood(
    "costco-hot-dog",
    "Food Court Hot Dog with Soda",
    "Costco",
    "1 hot dog and 20 fl oz soda",
    null,
    580,
    24,
    46,
    33,
  ),
  preparedFood(
    "costco-croissant",
    "Butter Croissant",
    "Costco Bakery",
    "1 croissant",
    null,
    300,
    6,
    35,
    17,
  ),
  preparedFood(
    "costco-greek-yogurt",
    "Organic Greek Yogurt, plain nonfat",
    "Kirkland Signature",
    "3/4 cup (170 g)",
    170,
    100,
    18,
    7,
    0,
  ),
  preparedFood(
    "costco-chicken-chunks",
    "Lightly Breaded Chicken Breast Chunks",
    "Kirkland Signature",
    "3 oz (85 g)",
    85,
    140,
    16,
    9,
    4.5,
  ),
  preparedFood(
    "costco-almonds",
    "California Sliced Almonds",
    "Kirkland Signature",
    "1/4 cup (28 g)",
    28,
    170,
    6,
    6,
    15,
  ),
  preparedFood(
    "sams-rotisserie-chicken",
    "Seasoned Rotisserie Chicken",
    "Sam's Club",
    "3 oz (85 g)",
    85,
    160,
    19,
    1,
    9,
  ),
  preparedFood(
    "walmart-rotisserie-chicken",
    "Traditional Rotisserie Chicken",
    "Marketside",
    "3 oz (85 g)",
    85,
    160,
    19,
    1,
    9,
  ),
  preparedFood(
    "whole-foods-rotisserie-chicken",
    "Classic Rotisserie Chicken",
    "Whole Foods Market",
    "3 oz (85 g)",
    85,
    170,
    21,
    0,
    9,
  ),
  preparedFood(
    "generic-rotisserie-chicken",
    "Rotisserie Chicken, meat and skin",
    "Generic",
    "3 oz (85 g)",
    85,
    170,
    22,
    0,
    9,
  ),
]

export function searchPreparedFoodCatalog(query: string, limit = 12): FoodSearchItem[] {
  return rankAndMergeFoodSearchResults(query, [PREPARED_FOOD_CATALOG], limit)
}
